@startuml

class Categoria {
  +id: int
  +nombre: string
}

class ProductoGenerico {
  +id: int
  +nombre: string
  +categoriaId: int
}

class Marca {
  +id: int
  +descripcion: string
}

class Presentacion {
  +id: int
  +descripcion: string
}

class Producto {
  +id: int
  +productoGenericoId: int
  +marcaId: int
  +presentacionId: int
  +puntoCriticoDeReposicion: int
  +rotacion: string
  +existencias: int
  +codigoDeBarra

  +calcularExistencias(): 
  +codigoDeBarras():
}

class Proveedor {
  +id: int
  +nombreContacto: string
  +razonSocial: string
  +telefono: string
  +correo: string
  +cuit: string
  +idLocalidad: int
  +idCondicionIva: int
}

class CondicionIva {
  +idCondicionIva: int
  +descripcion: string
}

class Localidad {
  +idLocalidad: int
  +idProvincia: int
  +descripcion: string
  +codigoPostal: string
  +caracteristica: string
}

class CondicionVentaProveedores {
  +idProveedor: int
  +idCondicionPago: int
  +descripcion: string
}

class CondicionDePago {
  +idCondicionPago: int
  +descripcion: string
}

class ProveedorProducto {
  +id: int
  +proveedorId: int
  +productoId: int
  +precio_unitario: int
}

ProductoGenerico "1" --> "1" Categoria
Producto "1" --> "1" ProductoGenerico
Producto "1" --> "1" Marca
Producto "1" --> "1" Presentacion

ProveedorProducto "*" --> "1" Proveedor
ProveedorProducto "*" --> "1" Producto

Proveedor "1" --> "1" CondicionIva
Proveedor "1" --> "1" Localidad

CondicionVentaProveedores "*" --> "1" Proveedor
CondicionVentaProveedores "*" --> "1" CondicionDePago
@enduml
